# Generated by Django 4.0 on 2021-12-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exeldocument',
            name='doc',
            field=models.FileField(upload_to='media'),
        ),
    ]
