# Generated by Django 4.0 on 2021-12-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_alter_import_data_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_data',
            name='unit_type',
            field=models.CharField(default='g', max_length=50),
        ),
    ]
