# Generated by Django 4.0 on 2021-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0004_import_data_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('recipe', models.TextField(max_length=2000)),
                ('method', models.TextField(max_length=2000)),
            ],
        ),
    ]
